name: Angular GitHub CI#

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js $
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
            
      - name: Install Dependencies
        if:
          steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm i
        
      - name: Build
        run: |
          npm run build

      - name: Login GitHub User
        run: |
          git --version
          git config user.name 'jdbench'
          git config user.email 'justin.d.bench@gmail.com'
          git config user.name
          git config user.email

      - name: Deploy
        run: |
          npm run deploy
          
